FROM tensorflow/tensorflow:1.13.1-gpu-py3
LABEL pocket parkinso service <parkinsondebolso@gmail.com>
COPY . /opt
WORKDIR /opt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
ADD https://parkinson-de-bolso-bucket.s3-sa-east-1.amazonaws.com/models/mask-rcnn-coco-model.h5 /opt/models/mask-rcnn-coco-model.h5
ADD https://parkinson-de-bolso-bucket.s3-sa-east-1.amazonaws.com/models/pocket-parkinson-model.hdf5 /opt/models/pocket-parkinson-model.hdf5
CMD ["nameko run service"]